server:
  port: 8081
spring:
  application:
    name: amq
  rabbitmq:
    host: 192.168.209.129

eureka:
  client:
    service-url:
      defaultZone: http://172.25.252.72:8761/eureka
  instance:
    prefer-ip-address: true